#! /usr/bin/env bash
set -eu # x

go get github.com/sheeley/tools/cmd/...

if [[ "$PRIVATE_CMD_DIR" != "" ]]; then
    (
        cd "$PRIVATE_CMD_DIR"
        git pull
        go install ./...
    )
fi