#! /usr/bin/env bash
set -eu

FILE="$TOOLS_DIR/scripts/$1"

if [[ -f "$FILE" ]]; then
	echo "script exists"
	exit 1
fi

cat <<EOD >>"$FILE"
#! /usr/bin/env bash
set -eu # x


EOD

chmod +x "$FILE"

# first, open code for the full repo
# $EDITOR "$GOPATH/src/github.com/sheeley/tools/"
# then open the file within that window
$EDITOR "$FILE"
