#! /usr/bin/env bash
set -eu

FILE="$GOPATH/src/github.com/sheeley/tools/scripts/$1"

if [[ -f "$FILE" ]]; then
    echo "script exists"
    exit 1
fi

cat <<EOD >> "$FILE"
#! /usr/bin/env bash
set -eu # x


EOD

chmod +x "$FILE"

# first, open code for the full repo
code "$GOPATH/src/github.com/sheeley/tools/"
# then open the file within that window
code "$FILE"