#! /usr/bin/env bash
set -eu

rm -f www.*/.DS_Store
PROFILE="aigee"

DIRS=$(ls -d www.*)
for DIR in $DIRS; do
	# setting PYTHONPATH as an empty string to prevent an issue where python 3
	# tries to use 2.7 libraries
	# echo "$DIR"
	OUTPUT=$(PYTHONPATH="" aws --profile "$PROFILE" s3 sync --dryrun --delete "$DIR" "s3://$DIR")

	if [ "$OUTPUT" != "" ]; then
		echo "$OUTPUT"
		echo "sync $DIR? [y/N]"
		read -r GO
		if [ "$GO" == "y" ]; then
			PYTHONPATH="" aws --profile "$PROFILE" s3 sync --delete --acl public-read "$DIR" "s3://$DIR"
		fi
	fi
done
