#! /usr/bin/env bash
set -eu

SERVICES='iamg   iamgm  iamgp  iamip  iamp   iampa  iamr   iamrp  iamu   iamup s3 r53r r53z'
for SERVICE in $SERVICES
do
    echo "$SERVICE"
    docker run \
        --rm \
        --name terraforming \
        -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
        -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
        -e AWS_REGION=us-east-1 \
        quay.io/dtan4/terraforming:latest \
        terraforming --tf-state "$SERVICE"
done